[package]
name = "image_compressor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.1"
mozjpeg = "0.9.2"
crossbeam-queue = "0.3.5"

[dev-dependencies]
fs_extra = "1.2.0"